# Generated by Django 3.0 on 2020-04-05 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('illness_no', models.CharField(db_column='illness_No', max_length=10, primary_key=True, serialize=False)),
                ('illness_name', models.CharField(blank=True, db_column='illness_Name', max_length=255, null=True)),
                ('ill_intro', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'illness',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('marker_no', models.CharField(db_column='marker_No', max_length=10, primary_key=True, serialize=False)),
                ('marker_name', models.CharField(blank=True, db_column='marker_Name', max_length=255, null=True)),
                ('marker_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('marker_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('illness_no', models.ForeignKey(blank=True, db_column='illness_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.Illness')),
            ],
            options={
                'db_table': 'marker',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MedMat',
            fields=[
                ('med_mat_no', models.CharField(db_column='med_mat No', max_length=10, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('med_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('med_mat_name', models.CharField(blank=True, db_column='med_mat Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'med_mat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_no', models.CharField(db_column='recipe_No', max_length=10, primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(blank=True, db_column='recipe_Name', max_length=255, null=True)),
                ('fangyi', models.CharField(blank=True, max_length=500, null=True)),
                ('classify', models.CharField(blank=True, max_length=255, null=True)),
                ('for_in_verse', models.CharField(blank=True, max_length=255, null=True)),
                ('comprise', models.CharField(blank=True, max_length=255, null=True)),
                ('provenance', models.CharField(blank=True, max_length=255, null=True)),
                ('usage', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'recipe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('symptom_no', models.CharField(db_column='symptom_No', max_length=10, primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(blank=True, db_column='symptom_Name', max_length=255, null=True)),
                ('symptom_per', models.CharField(blank=True, max_length=255, null=True)),
                ('sym_med_no', models.CharField(blank=True, db_column='sym_med_No', max_length=10, null=True)),
                ('illness_no', models.ForeignKey(blank=True, db_column='illness_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.Illness')),
                ('recipe_no', models.ForeignKey(blank=True, db_column='recipe_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.Recipe')),
            ],
            options={
                'db_table': 'symptom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('molecule_no', models.CharField(db_column='molecule_No', max_length=10, primary_key=True, serialize=False)),
                ('molecule_name', models.CharField(blank=True, db_column='molecule_Name', max_length=255, null=True)),
                ('molecule_formula', models.CharField(blank=True, max_length=255, null=True)),
                ('molar_mass', models.CharField(blank=True, db_column='molar mass', max_length=255, null=True)),
                ('molecule_str', models.CharField(blank=True, max_length=255, null=True)),
                ('synonyms', models.CharField(blank=True, max_length=255, null=True)),
                ('marker_no', models.ForeignKey(blank=True, db_column='marker_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.Marker')),
                ('med_mat_no', models.ForeignKey(blank=True, db_column='med_mat No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.MedMat')),
            ],
            options={
                'db_table': 'molecule',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='medmat',
            name='recipe_no',
            field=models.ForeignKey(blank=True, db_column='recipe_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.Recipe'),
        ),
        migrations.AddField(
            model_name='marker',
            name='med_mat_no',
            field=models.ForeignKey(blank=True, db_column='med_mat_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.MedMat'),
        ),
        migrations.AddField(
            model_name='illness',
            name='recipe_no',
            field=models.ForeignKey(blank=True, db_column='recipe_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.Recipe'),
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('gene_no', models.CharField(db_column='gene_No', max_length=10, primary_key=True, serialize=False)),
                ('gene_name', models.CharField(blank=True, db_column='gene_Name', max_length=255, null=True)),
                ('gene_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_alias', models.CharField(blank=True, max_length=255, null=True)),
                ('gene_intro', models.CharField(max_length=255)),
                ('ch_location', models.CharField(blank=True, max_length=255, null=True)),
                ('marker_no', models.ForeignKey(blank=True, db_column='marker_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.Marker')),
            ],
            options={
                'db_table': 'gene',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Efficacy',
            fields=[
                ('efficacy_no', models.CharField(db_column='efficacy_No', max_length=10, primary_key=True, serialize=False)),
                ('eff_name', models.CharField(blank=True, db_column='eff_Name', max_length=255, null=True)),
                ('eff_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('med_mat_no', models.ForeignKey(blank=True, db_column='med_mat No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.MedMat')),
                ('recipe_no', models.ForeignKey(blank=True, db_column='recipe_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.Recipe')),
            ],
            options={
                'db_table': 'efficacy',
                'managed': True,
            },
        ),
    ]
