# Generated by Django 3.0 on 2020-04-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medmat',
            name='med_mat_Latin_name',
            field=models.CharField(blank=True, db_column='med_mat Latin_Name', max_length=255, null=True),
        ),
    ]
