# Generated by Django 3.0 on 2020-04-19 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Graphapp', '0004_auto_20200419_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='efficacy',
            name='med_mat_no',
            field=models.ForeignKey(blank=True, db_column='med_mat_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.MedMat'),
        ),
        migrations.AlterField(
            model_name='medmat',
            name='med_mat_name',
            field=models.CharField(blank=True, db_column='med_mat_Name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='medmat',
            name='med_mat_no',
            field=models.CharField(db_column='med_mat_No', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='molecule',
            name='med_mat_no',
            field=models.ForeignKey(blank=True, db_column='med_mat_No', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Graphapp.MedMat'),
        ),
    ]
