# Generated by Django 3.0 on 2020-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphapp', '0005_auto_20200419_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medmat',
            name='function',
            field=models.CharField(blank=True, db_column='functions', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='usage',
            field=models.CharField(blank=True, db_column='usages', max_length=255, null=True),
        ),
    ]
