# Generated by Django 3.0 on 2020-05-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='diseasesName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
