# Generated by Django 3.0 on 2020-05-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Graphapp', '0002_auto_20200501_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='illness_no',
        ),
        migrations.RemoveField(
            model_name='symptom',
            name='recipe_no',
        ),
        migrations.DeleteModel(
            name='Efficacy',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
    ]
