# Generated by Django 3.0 on 2020-05-18 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphapp', '0003_auto_20200518_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
