# Generated by Django 3.0 on 2020-05-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphapp', '0004_recipe_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('diseases_no', models.CharField(db_column='diseases_No', max_length=10, primary_key=True, serialize=False)),
                ('diseases_name', models.CharField(blank=True, db_column='diseases_Name', max_length=255, null=True)),
                ('diseases_intro', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'diseases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Forcom',
            fields=[
                ('forcom_no', models.CharField(db_column='forcom_No', max_length=10, primary_key=True, serialize=False)),
                ('dosage1', models.CharField(blank=True, max_length=255, null=True)),
                ('dosage2', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
                ('formulas_no', models.CharField(blank=True, db_column='formulas_No', max_length=10, null=True)),
                ('herbs_name', models.CharField(blank=True, db_column='herbs_Name', max_length=255, null=True)),
            ],
            options={
                'db_table': 'forcom',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('formulas_no', models.CharField(db_column='formulas_No', max_length=10, primary_key=True, serialize=False)),
                ('formulas_name', models.CharField(blank=True, db_column='formulas_Name', max_length=255, null=True)),
                ('composition', models.CharField(blank=True, max_length=255, null=True)),
                ('provenance', models.CharField(blank=True, max_length=255, null=True)),
                ('zhuzhi', models.CharField(blank=True, max_length=255, null=True)),
                ('usage', models.CharField(blank=True, db_column='usages', max_length=255, null=True)),
                ('fufang', models.CharField(blank=True, max_length=255, null=True)),
                ('imliter', models.CharField(blank=True, max_length=511, null=True)),
                ('recfunction', models.CharField(blank=True, max_length=255, null=True)),
                ('fangyi', models.CharField(blank=True, max_length=511, null=True)),
                ('plusedreduced', models.CharField(blank=True, max_length=255, null=True)),
                ('recalias', models.CharField(blank=True, max_length=255, null=True)),
                ('cautioninuse', models.CharField(blank=True, max_length=255, null=True)),
                ('apply', models.CharField(blank=True, max_length=255, null=True)),
                ('for_in_verse', models.CharField(blank=True, max_length=255, null=True)),
                ('compatibilitycha', models.CharField(blank=True, max_length=255, null=True)),
                ('diffdiscuss', models.CharField(blank=True, max_length=255, null=True)),
                ('classify', models.CharField(blank=True, max_length=255, null=True)),
                ('identify', models.CharField(blank=True, max_length=511, null=True)),
                ('recmethod', models.CharField(blank=True, max_length=255, null=True)),
                ('interememory', models.CharField(blank=True, max_length=255, null=True)),
                ('mark', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'formulas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Herbs',
            fields=[
                ('herbs_no', models.CharField(db_column='herbs_No', max_length=10, primary_key=True, serialize=False)),
                ('herbs_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('herbs_name', models.CharField(blank=True, db_column='herbs_Name', max_length=255, null=True)),
                ('treatill', models.CharField(blank=True, max_length=255, null=True)),
                ('medclassify', models.IntegerField(blank=True, null=True)),
                ('taste', models.CharField(blank=True, max_length=255, null=True)),
                ('usdosage', models.CharField(blank=True, max_length=255, null=True)),
                ('plcha', models.CharField(blank=True, max_length=511, null=True)),
                ('plenvir', models.CharField(blank=True, max_length=255, null=True)),
                ('distribute', models.CharField(blank=True, max_length=255, null=True)),
                ('function', models.CharField(blank=True, db_column='functions', max_length=255, null=True)),
                ('machine', models.CharField(blank=True, max_length=255, null=True)),
                ('discuss', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('plclassify', models.CharField(blank=True, max_length=255, null=True)),
                ('compa', models.CharField(blank=True, max_length=255, null=True)),
                ('pinyin', models.CharField(blank=True, max_length=255, null=True)),
                ('toxicity', models.CharField(blank=True, max_length=255, null=True)),
                ('attention', models.CharField(blank=True, max_length=511, null=True)),
                ('medfun', models.CharField(blank=True, max_length=255, null=True)),
                ('checom', models.CharField(blank=True, max_length=255, null=True)),
                ('pmethod', models.CharField(blank=True, max_length=255, null=True)),
                ('annotation', models.CharField(blank=True, max_length=255, null=True)),
                ('capplication', models.CharField(blank=True, max_length=255, null=True)),
                ('anicha', models.CharField(blank=True, max_length=255, null=True)),
                ('stomethod', models.CharField(blank=True, max_length=255, null=True)),
                ('growth', models.CharField(blank=True, max_length=255, null=True)),
                ('statement', models.CharField(blank=True, max_length=255, null=True)),
                ('cultech', models.CharField(blank=True, max_length=255, null=True)),
                ('modesofrepro', models.CharField(blank=True, max_length=255, null=True)),
                ('anikind', models.CharField(blank=True, max_length=255, null=True)),
                ('latin', models.CharField(blank=True, max_length=255, null=True)),
                ('bcpre', models.CharField(blank=True, max_length=511, null=True)),
                ('plregion', models.CharField(blank=True, max_length=255, null=True)),
                ('taboo', models.CharField(blank=True, max_length=255, null=True)),
                ('manmade', models.CharField(blank=True, max_length=255, null=True)),
                ('modresearch', models.CharField(blank=True, max_length=255, null=True)),
                ('resourcedis', models.CharField(blank=True, max_length=255, null=True)),
                ('mineralcha', models.CharField(blank=True, max_length=255, null=True)),
                ('mineralkind', models.CharField(blank=True, max_length=255, null=True)),
                ('mineralenvir', models.CharField(blank=True, max_length=255, null=True)),
                ('aniregion', models.CharField(blank=True, max_length=255, null=True)),
                ('mineralnat', models.CharField(blank=True, max_length=255, null=True)),
                ('mainkind', models.CharField(blank=True, max_length=255, null=True)),
                ('proarea', models.CharField(blank=True, max_length=255, null=True)),
                ('toxeffect', models.CharField(blank=True, max_length=255, null=True)),
                ('adverserea', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'herbs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_no', models.CharField(db_column='target_No', max_length=10, primary_key=True, serialize=False)),
                ('target_name', models.CharField(blank=True, db_column='target_Name', max_length=255, null=True)),
                ('target_cat', models.CharField(blank=True, max_length=255, null=True)),
                ('target_intro', models.CharField(blank=True, max_length=255, null=True)),
                ('diseasesName', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'target',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='illness',
            name='recipe_no',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='illness_no',
        ),
        migrations.RemoveField(
            model_name='marker',
            name='med_mat_no',
        ),
        migrations.DeleteModel(
            name='Reccom',
        ),
        migrations.RemoveField(
            model_name='gene',
            name='marker_no',
        ),
        migrations.DeleteModel(
            name='Illness',
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
        migrations.DeleteModel(
            name='MedMat',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
