# Generated by Django 3.0 on 2020-05-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Graphapp', '0007_auto_20200521_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forcom',
            name='formulas_no',
            field=models.CharField(blank=True, db_column='formulas_No', max_length=40, null=True),
        ),
    ]
